---
- hosts: all
  tasks:
    - name: bootstrap ansible packages with existing apt state
      sudo: true
      apt: pkg={{ item }} state=present
      with_items:
        - aptitude
        - apt-transport-https

    - name: install docker GPG key
      sudo: true
      apt_key: state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x36A1D7869245C8950F966E92D8576A8BA88D21E9"

    - name: ensure the docker apt repository is added
      sudo: true
      apt_repository: state=present repo='deb https://get.docker.io/ubuntu docker main'

    - name: install rsyslog.conf
      sudo: true
      copy: src=files/rsyslog/rsyslog.conf dest=/etc/rsyslog.conf

    - name: install joyent GPG key
      sudo: true
      apt_key: state=present url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

    - name: ensure the joyent nodejs apt repository is added
      sudo: true
      apt_repository: state=present repo='deb https://deb.nodesource.com/node precise main'

    - name: update and safe upgrade apt-get packages
      sudo: true
      apt: update_cache=true cache_valid_time=3600 upgrade=safe

    - name: install main system packages
      apt: pkg={{ item }} state=present
      sudo: true
      with_items:
        - python-pycurl #NOTE: these python modules are for ansible
        - python-mysqldb
        - python-apt
        - python-pip
        - linux-image-generic
        - linux-headers-generic
        - console-setup
        - vim
        - debootstrap
        - lxc-docker
        - postfix
        - mailutils
        - rsyslog
        - nodejs
        - build-essential
        #- npm
        # - update-manager-core
        # - update-notifier-common
        # - git
        # - screen
        # - psmisc
        # - curl
        # - zip
        # - rsync
        # - wget
        # - openjdk-7-jre
        # - htop
        # - tree
        # - kbd
        # - xkb-data
        # - man-db
        # - libc-bin
        # - dnsutils
        # - pv
        # - libssl1.0.0
        # - openssl
        # - libssl-dev
        # - nodejs
        # - libpcap0.8
        # - tcpdump
        # - apache2-utils
        # - libapr1
        # - libaprutil1

    - name: install virtualbox system packages
      apt: pkg={{ item }} state=latest
      sudo: true
      with_items:
        - virtualbox-guest-utils
      when: inventory_hostname in groups['virtualbox']

    - name: remove un-needed packages
      apt: pkg={{ item }} state=absent
      sudo: true
      with_items:
        - libkms1
        - hicolor-icon-theme
        - sound-theme-freedesktop
        - libbonobo2-common
        - libbonobo2-0
        - libtdb1
        - libidl-common
        - libgnome2-common
        - libidl0
        - libvorbisfile3
        - liborbit2
        - gamin
        - libgamin0
        - python-gamin
        - chef
        - puppet
        - puppet-common
        - libgl1-mesa-dri
        - libllvm3.0
        - language-pack-gnome-en
        - language-pack-gnome-en-base
        - xfonts-base
        - linux-firmware
        - linux-image-generic
        - linux-image-server
        - linux-server
        - memtest86+
        - ubuntu-standard
        - virtualbox-guest-x11
        - xserver-xorg-core
        - libxfixes3
        - libxcomposite1
        - x11-xkb-utils
        - libxfont1
        - libpixman-1-0
        - libxaw7
        - libice6
        - libxmu6
        - libxpm4
        - libxrender1
        - libfontenc1
        - x11-common
        - libsm6
        - libxdamage1
        - libxt6
        - libxrandr2
        - libxkbfile1
        #NOTE: does not reboot!
        #- libfreetype6
        #- libx11-6
        #- libxext6
        #- libxmuu1
        #- xauth
        #- grub-common #NOTE: caution!!
        #- grub-gfxpayload-lists
        #- grub-pc
        #- grub-pc-bin
        #- grub2-common
        #- apparmor #NOTE: has issues on ubuntu 14.x
        #- libapparmor1
        #- libapparmor-perl

    - name: install dkill alias
      lineinfile: dest=~/.bashrc state=present line="alias dkill=\"sudo docker kill \$(sudo docker ps | grep -v CONTAINER | awk '{ print \$1 }')\""

    - name: install dwatch alias
      lineinfile: dest=~/.bashrc state=present line="alias dtop=\"watch -n 0.1 sudo docker top \$(sudo docker ps | grep -v CONTAINER | awk '{ print \$1 }')\""

    - name: install postfix master.cf
      sudo: true
      copy: src=files/postfix/master.cf dest=/etc/postfix/master.cf

    - name: clear docker init
      sudo: true
      shell: rm -Rf /etc/docker_init

    #- name: install foreman created upstart files
    #  local_action: command bundle exec foreman export ansible/files/docker_init

    - name: install docker init
      sudo: true
      copy: src=files/docker_init/ dest=/etc/docker_init

    - name: ensure postfix is started
      sudo: true
      service: name=postfix state=stopped enabled=true

#    - name: ensure inn2 is started
#      sudo: true
#      service: name=inn2 state=stopped enabled=true

    - name: unset immutable attribute for etc/hostname file to allow modification
      sudo: true
      shell: chattr -i /etc/hostname

    - name: setup hostname according to inventory
      sudo: true
      hostname: name={{ inventory_hostname }}

    - name: set etc/host for hostname
      sudo: true
      lineinfile: dest=/etc/hosts line="127.0.0.1 {{ inventory_hostname }}"

    - name: set immutable attribute for etc/hostname file to prevent modification
      sudo: true
      shell: chattr +i /etc/hostname

    - name: install nodejs app
      shell: "{{ item }}"
      with_items:
        - mkdir -p ~/node_modules
        - rm -Rf ~/current
        - git clone /vagrant ~/current
        - cd ~/current && ln -sf ~/node_modules node_modules
        - cd ~/current && npm install

    - name: bootstrap docker image
      sudo: true
      shell: "{{ item }}"
      ignore_errors: true
      with_items:
        - /etc/init.d/rsyslog stop
        - /etc/init.d/postfix stop
        - stop cron
        - stop atd
        - test -e /proc/sys/kernel/yama/protected_nonaccess_hardlinks && echo 0 > /proc/sys/kernel/yama/protected_nonaccess_hardlinks
        - rm -f /etc/init.d/ondemand
        - rm -f /etc/rc2.d/S99ondemand
        - rm -f /etc/rc4.d/S99ondemand
        - rm -f /etc/rc5.d/S99ondemand
        - rm -f /home/provision/.bash_history
        - rm -f /root/.bash_history
        - docker ps -a | cut -d' ' -f1 | grep -v CONTAIN | xargs -I{} docker rm -f {}
        - docker images | grep -v CREATED | awk '{ print $3 }' | xargs -I{} docker rmi -f {}
        - find /var/log -type f | xargs -i{} bash -c "echo | tee {}"
        - rm -f /home/provision/precise.tar
          #--exclude=/var
        - >
          tar --numeric-owner --exclude=/initrd.img
          --exclude=/initrd.img.old
          --exclude=/lost+found
          --exclude=/media
          --exclude=/vmlinuz
          --exclude=/vmlinuz.old
          --exclude=/vagrant
          --exclude=/proc
          --exclude=/sys
          --exclude=/dev
          --exclude=/etc/init
          --exclude=/usr/src
          --exclude=/run
          --exclude=/boot
          --exclude=/mnt
          --exclude=/srv
          --exclude=/etc/rc3.d/S20virtualbox-guest-utils
          --exclude=/etc/rc3.d/S23ntp
          --exclude=/etc/rc3.d/S30vboxadd
          --exclude=/etc/rc3.d/S30vboxadd-x11
          --exclude=/etc/rc3.d/S35vboxadd-service
          --exclude=/etc/rc3.d/S50rsync
          --exclude=/etc/rc3.d/S70dns-clean
          --exclude=/etc/rc3.d/S70pppd-dns
          --exclude=/etc/rc3.d/S75sudo
          --exclude=/etc/rc3.d/S99grub-common
          --exclude=/etc/rc3.d/S99ondemand
          --exclude=/etc/rc3.d/S99rc.local
          --exclude=/etc/rc0.d
          --exclude=/etc/rc1.d
          --exclude=/etc/rc2.d
          --exclude=/etc/rc4.d
          --exclude=/etc/rc5.d
          --exclude=/etc/rc6.d
          --exclude=/etc/rc.local
          --exclude=/etc/rcS.d
          --exclude=/home/{{ ansible_ssh_user }}/postinstall.sh
          -cf precise.tar /
        - cat precise.tar | docker import - precise
        #- docker run --detach=true -p 4443:443 -p 8080:80 -p 4406:3306 -p 4407:3307 -p 2222:22 -p 9119:119 precise /sbin/init --confdir=/etc/docker_init --startup-event=filesystem --no-dbus --verbose
